apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: diagrams-tls
  namespace: diagrams
spec:
  secretName: diagrams-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - diagrams.romaine.life
