apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-shared
  namespace: diagrams
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: c1ae25a3-e389-4af8-99e4-d4d0baa10fd8
